# Generated by Django 4.2.3 on 2023-08-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeitems',
            options={'verbose_name': 'آیتم ویژگی', 'verbose_name_plural': 'آیتم های ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'ویژگی محصول', 'verbose_name_plural': 'ویژگی های محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productinventory',
            options={'verbose_name': 'موجودی محصول', 'verbose_name_plural': 'موجودی محصولات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='attribute_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='store.attributeitems', verbose_name='ویژگی مربوطه'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='income_time',
            field=models.DateField(auto_now_add=True, verbose_name='زمان ورود به انبار'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='store.products', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='ProductOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductions_from_stock', models.IntegerField(verbose_name='تعداد کسر از انبار')),
                ('outcome_time', models.DateField(auto_now_add=True, verbose_name='زمان خروج از انبار')),
                ('product_inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='store.productinventory', verbose_name='موجودی')),
            ],
            options={
                'verbose_name': 'کسری محصول',
                'verbose_name_plural': 'کسری محصولات',
            },
        ),
    ]
