# Generated by Django 4.2.3 on 2023-08-10 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_attributeitems_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='unit',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='unit',
            field=models.CharField(default='عدد', max_length=50),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv', to='store.products', verbose_name='محصول'),
        ),
    ]
